### ISSUE TITLE
Show USD Equivalent on Contribution

### ISSUE THREAD

**Issue by sceenius** [hypha-dao/dho-web-client#114]
When opening the view form, show USD Equivalent in the header for NON CUSTOM AMOUNTS- 

SALARY CALCULATION (BASED ON USD EQUIVALENT OF USD XXXXX)

For CUSTOM amounts show

SALARY CALCULATION (BASED ON A CUSTOM TOKEN AMOUNT)

(See also the heading in the Assignment form)

**Comment by gregory-latinier** [comment]
The task doesn't really make sense.
We only have custom tokens now.
Like I said, in order to simplify the smartcontract interactions, I only send the tokens now. The USD and deferred fields are UI helpers to guide the user in filling the tokens fields. 
That way I'm sure to avoid any differences between the UI and the smartcontract.

I suggest that we close this issue

**Comment by sceenius** [comment]
Yes, makes sense. Let's close this.
