### ISSUE TITLE
Generic Contribution not showing up in search

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#1513]
Reproduce:
1. Go to "Search DAO" and look for e.g. Zoom

Expected behaviour:
see this proposal in the list: https://dao.hypha.earth/hypha/proposals/28670

Experienced behaviour:
The proposal doesnt show in the list (I tried all filters, archived, active, etc...)

https://eosauthority.com/transaction/aa256a7cc1b6d49946ded04cd51a81e6dee67ab0d5cbd1c34b3975fd4611e93f?network=telos

**Comment by evgenibir** [comment]
@leonieherma1 

Looks like I found it on the 2nd page of the search results:

https://dao.hypha.earth/hypha/search?q=Zoom&filter=Active&order=%5Bobject%20Object%5D

Filter is `Active`

Result lines in Total: `15`

This proposal is the item 15 from the Total list.

https://dao.hypha.earth/hypha/proposals/28670

[EXPENSE] Zoom + Zapier Reimburse 

Cash Token (HUSD) $2,499

**Comment by leonieherma1** [comment]
@evgenibir I see, but then the title is different from the preview (card) to the actual title on the detail page:

<img width="1049" alt="image" src="https://user-images.githubusercontent.com/75991832/186479487-741a8ce2-5f09-4a97-b5d1-cb2c3fe0261b.png">
<img width="954" alt="image" src="https://user-images.githubusercontent.com/75991832/186479527-01f73818-5138-45dc-acc5-ae5d4fb3e7b3.png">

therefore the confusion

**Comment by evgenibir** [comment]
@leonieherma1 Yes, I see it too.

The correct title of proposals-14729 is `[EXPENSE] Zoom + Zapier Reimburse`

but on `Search results` page it shows wrong title `[QUEST] SEEDS Thrivability Compass, Constitution, Facilitation` of some another proposal.

The **issue with wrong title also exist** for some other proposals too.

There are another **issue with wrong `HUSD` amount** too (Instead of `HUSD` it shows a value from `Voice Token` amount)

I will able to fix this issue during next week after my current stuff.
