### ISSUE TITLE
[badge] Activation gives error message

### ISSUE THREAD

**Issue by sceenius** [hypha-dao/dho-web-client#178]
When activating a badge-assignment I get 

dao.hypha_closedocprop
could not insert object, most likely a uniqueness constraint was violated: pending console output:

**Comment by gregory-latinier** [comment]
@dappdever this is probably a smartcontract issue, here is the hash that throw the error "183E634E3825018CB1AFDB899F544DC9C0E3B99DF85ED52F226C291EBFF3CFA2"

**Comment by dappdever** [comment]
> When activating a badge-assignment I get
> 
> dao.hypha_closedocprop
> could not insert object, most likely a uniqueness constraint was violated: pending console output:

I improved the error message on this.  It is attempting to add the same badge to the same member. 

```
An edge named holdsbadge already exists  from 71836b83d367ab992b58d3704efd7e9d4d36b28e90bd89ecee82415f7ca34528 to 1fc633347393d8ebf76ccd639da2e03d4934ffda4ff3f71211c648e53435e6ec"
```

Badge assignment creates this structure on the graph:
``` c++
//    member    ---- holdsbadge     ---->   badge
//    member    ---- assignbadge    ---->   badge_assignment
//    badge       ---- heldby         ---->   member
//    badge       ---- assignment     ---->   badge_assignment
```

It is a valid use case because the ```badge_assignment``` could have different dates (as an extension).  I will update to the code to NOT fail in this case.  If the edges of "heldby" and "holdsbadge" already exist, it will simply skip over trying to create them.

**Comment by sceenius** [comment]
This works for me now, you can move the complete if ok @dappdever
