### ISSUE TITLE
Policy Change: Hypha Game to add OKR's as proposal requirements

### ISSUE THREAD

**Issue by sceenius** [hypha-dao/dho-web-client#190]
We implement the OKR pattern for assignments and contributions by modifying the current templates for both forms. 

**Current assignment template text:**

Please describe in a paragraph or two why you are a good fit for this role. We recommend to add a link to a video, CV, or other supporting documents.

Replace text with:

Hypha applies a pattern of **Objectives and Key Results (OKRs)** to all assignments. At the beginning of your assignment, state your **Objective**  (e.g. "Have a thriving community on SEEDS"), which is something that you and/or your circle hope to accomplish within the next quarter _as well as_ **2-5 Key Results**, which are measurable expressions of success or progress towards this objective (e.g. "Invite 100 new Residents"). At the time of your re-evaluation, write down how much of your KR you completed towards your Objective (e.g. "80% completed"). Then, repeat the process for the next quarter assignment, keeping the previous OKRs for reference. We recommend to add a link to a video, CV, or other supporting documents, below.

Shorter version:

Hypha applies a pattern of **Objectives and Key Results (OKRs)** to all assignments. At the beginning of your assignment, state your **Objective**  (something that you and/or your circle hope to accomplish) as well as **2-5 Key Results** (measurable expressions of success or progress towards this objective). At the time of your re-evaluation, write down how much of your KR you completed towards your Objective. Repeat the process for the next quarter assignment, keeping the previous OKRs for reference. We recommend to add a link to a video, CV, or other supporting documents, below.

**Current contribution template text:**

Please describe in a paragraph or two why you are getting this payout. We recommend to add a link to other supporting documents in the text box below.

Replace text with:

Hypha applies a pattern of **Objectives and Key Results (OKRs)** to all contributions. Please state the **Objective** (something you hoped to accomplish) as well as **2-5 Key Results*** for this contribution, which are measurable expressions of success justifying this payment. We also recommend to add a link to other supporting documentation in the text box below.

---
From Julio:
OKRs or "**Objectives and Key Results"** are a collaborative planning tool used by teams and individuals to set challenging goals backed by measurable results.

They were invented by Andy Grove at Intel and perfected at Google after 1999.

- **Objective**: something that you hope to accomplish so that at a later time written in a way that you can easily tell if you have reached it.
- **Key Result**: Measurable expressions of success or progress towards an Objective. Each KR is a Metric. This is very important for data driven organizations to have numerical clarity on what matters
- An OKR is an agreement, so it's very important to clearly define a *time frame* where the Objectives are supposed to be completed, usually a quarter or more
- Each Objetive *always come paired* with 2-5 Key Results, and you define them BEFORE doing what you intend, so you don't use OKRs to describe your post success
- Objectives can be commited or aspirational (moonshots), I usually prefer moonshots, so it's ok to aim high and actually complete less than you aimed for, so you can recognize a brilliant success when you see one
- It usually works best to define OKRs for teams, circles or projects, less for individuals, and usually each KR has someone assigned for reporting, or is extracted automatically from a dashboard, it's best practice to review each KR metric at start of every Circle meeting
- There are some pretty strong arguments on not having compensation or bonuses tied to OKRs, as it drives extrinsic motivation and leads to reward driven mentality, comparisons and unhealthy competition

---

Add OKR’s (Objectives and Key Results) to all funding proposals. 

For Assignments having the Objective (what the member intends to do with that assignment for the stated period) for any assignment - if it’s an assignment extension to have a section for “Key Results” where the member shares the results of the last Assignment. 

This proposal is change how contributions are tracked. Suggesting we don’t track time (e.g. spent 2 hours on a call). But instead we just track what was accomplished (Key Results). This way its much simpler for people to report what they have been doing in a contribution or an Assignment and just sharing the Key Results of their activity over the given period. 

This way we can track collective progress and get a clearer picture of what is being accomplished with the funds requested to give more information to voters! 

https://discordapp.com/channels/722537361480613950/722558048165429399/773111921016569867

---

Per Riekie: https://discord.com/channels/722537361480613950/758682282663477279/775718996602388481

Want to elaborate on a Policy that was recently passed in the DHO about the process for contributions, Assignments or any form of value claim from Hypha. This is to move towards more clarity and simplification of the accounting and contribution process in Hypha.

All Assignments (extensions or otherwise) or contribution requests can use the OKR (Objective and Key Results) model (video from @Julio Holon coming soon :slight_smile: ) 

In essence - when applying for an assignment or contribution- speak to what you intend to do (as concrete as possible e.g. what is your objective in this role over that time and what would "key results" be) This is what we'll measure against for ongoing assignments or contributions. 

For people holding roles - this is only something that need happen each quarter (so shouldn't be too time consuming as we share what beautiful things we did last quarter and what we intend to do the next quarter). For all those doing contributions - this is simply:

What was your contribution? 

e.g. what value did Hypha gain from you that you're claiming value for?

This is how we'll measure if that value being requested is equal to the value given to Hypha. The more we can balance this equation the more successful we will be!

I urge all members to vote depending on the alignment of these values. :slight_smile:

**Comment by juliolrmonteiro** [comment]
Here's a summary about my best practices for designing OKRs:
https://www.notion.so/OKRs-30da503c4c7a475fb5399e15ee13255f
And here's the video:
https://youtu.be/_bvMn8Tf9-8

**Comment by juliolrmonteiro** [comment]
Hey there @sceenius,

According to what I learned on my experience on best practices using OKRs, a "Key Result" should not be treated as "results" that you achieved from your previous iteration. An O-KR never come separated, you shouldn't define "O" first and then "KR" later to prove you accomplished your Os.

An OKR is a contract on **what**(O) you are going to achieve and **how to measure achievement**(KR), that's why they are never separated. 

So, I would like to propose some changes to the texts:

**Current assignment template text:**

Please describe in a paragraph or two why you are a good fit for this role. We recommend to add a link to a video, CV, or other supporting documents.

Replace text with:

Hypha applies a pattern of Objectives and Key Results (OKRs) to all assignments. At the beginning of your assignment, state your Objectives, that is a list of what you and/or your your circle hope to accomplish within the next quarter or so in the scope of that given assignment (e.g. Have a thriving community on SEEDS), then for each Objective write 2-5 Key Results, which are measurable expressions of success or progress towards each objective (e.g. Invite 100 new Residents). At the time of your re-evaluation, write down how far(%) you went on each KR, that will give an overall rating of each Objective. Then, repeat the process for the next quarter assignment, keeping the previous OKRs for reference. We also recommend to add a link to other supporting documentation in the text box below.

**Current contribution template text:**

Please describe in a paragraph or two why you are getting this payout. We recommend to add a link to other supporting documents in the text box below.

Replace text with:

Hypha applies a pattern of Objectives and Key Results to all contributions. Please state the Objectives (and 2-5 Key Results for each) aligned with the circle OKRs, that were accomplished by this contribution, making clear how each Key Result was affected for each Objective, to justify this payment. We also recommend to add a link to other supporting documentation in the text box below.

**Comment by sceenius** [comment]
@juliolrmonteiro I've changed the description following your outline, with the exception of multiple objectives, I want to keep things simple at this point and the description is fairly long and elaborate already. See the shorter version.
