### ISSUE TITLE
Sliding Design Feedback

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#1906]
@luigicarlini1988 you can add the sliding design feedback here

**Comment by luigicarlini1988** [comment]
- Next button: sometimes doesn't trigger the animation/auto slide to the next step
- when user manually "scrolls" to a previews step, we should display an "Edit" button, instead of an inactive "next" button

- mobile, 
-- i suggest we review the design of the bottom sheets and only display:
----- steps count (left)
---- next button (right)
-- "save as draft" button, let's place it in form of an icon, near to the "X" (close) top-right button

See document for detail:
https://docs.google.com/document/d/1c4cvxbfhCPxyLVHLMaL2HreKZ6hAJu7yB55mbhf9tpU/edit
