### ISSUE TITLE
Modified redemption process

### ISSUE THREAD

**Issue by sceenius** [hypha-dao/dho-web-client#221]
Per Nik, our exchange contract tlosto.seeds now accepts Hypha's HUSD token. When you send HUSD to tlosto.seeds it sends you back Seeds based on the current exchange rate.

We need to modify the UI to redeem Seeds in addition to BTC, ETH and EOS.

We can ADD a new entry on the profile form, redemption section. and set the default to SEEDS. This will trigger the redemption to convert HUSD to SEEDS.

![image](https://user-images.githubusercontent.com/24725582/102912886-f777ed80-444b-11eb-8609-12c3fc73cb55.png)

**Comment by n13** [comment]
It does not need to be in the additional redemption section as there's nothing to enter there.

If people have a different Seeds user account than their hypha dao account then... well then they need to send the HUSD from their seeds user account.

The transaction is 

accountA -> transfers HUSD to tlosto.seeds
tlosto.seeds -> transfers SEEDS to accountA

I propose a new tab that's the same as the redeem tab, except call it "buy" and make it transfer the HUSD to tlosto.seeds. As a safety check, check that the hypha DAO Telos account is also a Seeds account. 

Because it's possible to have a DHO account that's different from Seeds account. 

Really one more of these
![image](https://user-images.githubusercontent.com/65412/102914507-56288000-44bb-11eb-8a93-b3519ddc9c59.jpeg)

Except it says "Buy Seeds with HUSD" instead of HUSD... something like that?

**Comment by n13** [comment]
Alternatively you could use this API to show a QR code which Anchor or Seeds Light Wallet or I also think Passport can scan and issue the transaction

That API takes an amount (HUSD amount), and generates a transaction to buy Seeds with HUSD - the signer of the transaction is the executor as well, meaning if I sign this QR code as illumination, it will send HUSD from illumination and receive SEEDS to illumination. If Alex signs it as cometogether, then HUSD will be sent from cometogether... 

```
http://api-esr.hypha.earth/buyseeds?quantity=1
```

**Comment by sceenius** [comment]
@n13 I see what you mean. To me there is no difference in what you buy, the user selects that, why give SEEDS a priority?

* buy Seeds with HUSD
* buy EOS  with HUSD
* buy BTC with HUSD
* buy ETH with HUSD
* ... etc etc 

So, I think to see this as a preference setting is easier, rather than a promotional feature ("buy SEEDS now"). Cleaner UI imo, and yes we can default the current SEEDS account (or option to have others which I think is the case for many in the future).

**Comment by sceenius** [comment]
@n13 The QR feature in the Light Wallet is cool.

**Comment by n13** [comment]
You have a point there with EOS, etc. The only difference is all these other currencies need extra information (addresses, accounts) and go through the treasury rather than being automated. 

Seeds doesn't need extra information, and is automated. 

But I see what you mean - Seeds should be treated like other currencies, that makes sense.

**Comment by sceenius** [comment]
Let's do the quick fix first since it is way easier to redeem that way. Maybe the others can follow that process too OR larger HUSD>Seeds transfers go through the treasury process.

**Comment by gregory-latinier** [comment]
This is already in production
There is a BUY SEEDS button that sends HUSD to tlosto.seeds and send some SEEDS back to the user
