### ISSUE TITLE
[R] Cannot close (activate) badge

### ISSUE THREAD

**Issue by sceenius** [hypha-dao/dho-web-client#333]
Expected: Closing a badge (via activate button) closes the badge
Actual: see error message below, example Dannie's badge for facilitator

closedocprop
could not insert object, most likely a uniqueness constraint was violated: pending console output:

```User: joachimstroh
Action: 0
Contract: dao.hypha
Method: closedocprop
Data: {"proposal_hash":"02D251B006490870F4C50566E33547B6E1174075565EC1E3D3B8ABC71997AB8B"}
```

**Comment by dappdever** [comment]
The user (seeding1love) receives the error because they already have a badge assignment for the facilitator badge. It looks they have applied twice:  

![image](https://user-images.githubusercontent.com/32852271/112876065-07c6e680-9093-11eb-9bdf-13c0934675c9.png)

I erased this document so that the user does not need to attempt to close the proposal.
