### ISSUE TITLE
Add a technical dialog for objects

### ISSUE THREAD

**Issue by gregory-latinier** [hypha-dao/dho-web-client#47]
On the sidebar view, add a cog icon on the top right that will open a dialog

The data is displayed as a flat table key / value pair
For huge value add a toggle icon to switch between the full data and a truncated version of the 100st chars
By default the data is truncated

**Comment by dappdever** [comment]
This screen that renders the grid view should also allow for 2 inputs.  "scope" as a drop-down that is populated by the "get_table_scopes" (I can check the eosjs command for this) and an integer for the "ID".  Users can enter these, and the object corresponding to this will be rendered in the view.  

The view should support direct links (not sure if that is the right word), so that a text link can be pasted and come back exactly to that grid view.  Either parameters or something like: https://dho.hypha.earth/assignment/42

**Comment by dappdever** [comment]
daoctl has a similar command, where the 2 inputs are scope and ID:
![image](https://user-images.githubusercontent.com/32852271/91553310-301f1480-e8fb-11ea-8497-17084b9aa88e.png)

**Comment by dappdever** [comment]
- If the field name ends in "x100", render it as a percentage.
- For "start_period" and "end_period", show the start date for start_period and end date of end_period.

- It can skip over the ```trxs``` and ```floats``` arrays
- It should show ```created_date``` and ```updated_date```

**Comment by gregory-latinier** [comment]
If the field name ends in "x100", render it as a percentage. => I've added a '%'

For "start_period" and "end_period", show the start date for start_period and end date of end_period. => OK

It can skip over the trxs and floats arrays => OK

It should show created_date and updated_date => It's already there, every fields are pulled out and flatten unless explicitly excluded like trx and floats

**Comment by sceenius** [comment]
Looks good.
