### ISSUE TITLE
Enforce EOS memo, change memo format

### ISSUE THREAD

**Issue by n13** [hypha-dao/dho-web-client#509]
## Spec

Add more verification to EOS addresses entered by users

Make it more difficult to screw this up both on the frontend and backend

It is crucially important that people enter their EOS accounts and memos correctly

Let's figure out the top 10 crtypto exchanges and when a user enters an EOS address that's one of these exchanges, enforce the memo as mandatory field. 

## Implementation
When we detect an exchange EOS account, make sure user enters memo
When user enters a new EOS account, make sure to wipe the old memo
Store the memo as part of the EOS address, like so: 
binancecleos:1122334455
This makes it easier for the backend to parse and less error prone. 

## Additional Information
Top 10 exchanges ranked by volume:

https://coinmarketcap.com/rankings/exchanges/

Known accounts (add to the list plz)
```
coinbasebase
binancecleos
krakenkraken
```

**Comment by lukegravitt** [comment]
Most of this is fairly straightforward, but I don't agree with this change:

> Store the memo as part of the EOS address, like so:
binancecleos:1122334455
This makes it easier for the backend to parse and less error prone.

This is a breaking change on the frontend, and requires special detection or a synchronized data update with the backend. I also think that storing 2 values into a single variable with custom syntax is poor practice and much more likely to be error prone since it requires knowledge of how the data is organized (the key/variable name `eosmemo` is lost so now you'd have to know what the value after the : meant).
