### ISSUE TITLE
show no votes in red

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dho-web-client#886]
show no votes in red like in the current DHO:

<img width="621" alt="image" src="https://user-images.githubusercontent.com/75991832/160510776-cf99cb07-cade-4697-a92a-9dee7bb2373a.png">

**Comment by jmgayosso** [comment]
Hi @leonieherma1 Do you want to implement this on all places where appear the bars?? or just in proposal list when the proposal is opened??? I mean in the vote widget for example I think is a bad option because the background is not white, this is an example for rejected proposal
![Screen Shot 2022-03-29 at 13 39 52](https://user-images.githubusercontent.com/58195358/160693858-6ad9c3dc-d79a-404a-a7ea-2fded175c9ee.png)

**Comment by leonieherma1** [comment]
@jmgayosso good point... ok let's just do it on the proposal list for now and in the profile (while the proposal is open for voting). Not in the proposal detail page.....

Thanks

**Comment by leonieherma1** [comment]
@jmgayosso actually let's do the proposal detail page too, when the voting is still open:
<img width="321" alt="image" src="https://user-images.githubusercontent.com/75991832/160745347-0ce7ca31-c338-408b-a11c-53f288e27dcd.png">
 let's just NOT do it when the voting is finished
